# docker-compose.dev.yml

version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: yec-dev
    ports:
      - "7070:7070" # Localhost:7070 → Container7070
    volumes:
      - .:/app       # Hot reload
      - /app/node_modules # Exclude local node_modules
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=7070
    restart: unless-stopped
